std::string shape2d_vs = 
"#version 330 core\n"
"\n"
"layout(location = 0) in vec2 position;\n"
"layout(location = 1) in vec4 vertCol;\n"
"layout(location = 2) in vec2 uvCoords;\n"
"\n"
"uniform vec2 translation;\n"
"uniform vec2 origin;\n"
"uniform float zlayer;\n"
"uniform vec2 angle;\n"
"uniform vec2 scale;\n"
"\n"
"uniform vec2 v2screen;\n"
"uniform vec2 v2screenscale;\n"
"uniform vec2 v2screenoffset;\n"
"\n"
"out vec4 vertcolor;\n"
"out vec2 uvs;\n"
"\n"
"void main() {\n"
"\n"
"   vertcolor = vertCol;\n"
"   uvs       = uvCoords;\n"
"\n"
"   vec2 finalOrig = position - origin;\n"
"        finalOrig *= (scale*v2screenscale);\n"
"\n"
"   vec2 finalPos = vec2( finalOrig.x * angle.x + finalOrig.y * (-angle.y), finalOrig.x * angle.y + finalOrig.y *  angle.x);\n"
"        finalPos += (translation*v2screenscale) + v2screenoffset;\n"
"\n"
"   gl_Position = vec4(finalPos / v2screen - vec2(1, -1) ,zlayer , 1);\n"
"\n"
"};\n"
;


std::string shape2d_fs = 
"#version 330 core\n"
"\n"
"out vec4 color;\n"
"\n"
"uniform vec4 drawcolor;\n"
"uniform sampler2D mytexture;\n"
"uniform float texture_enable;\n"
"\n"
"in vec4 vertcolor;\n"
"in vec2 uvs;\n"
"\n"
"void main() {\n"
"	color = \n"
"      ((texture_enable * texture(mytexture, uvs)) \n"
"        + ((1.0 - texture_enable) * vec4(1.0, 1.0, 1.0, 1.0)))\n"
"        * drawcolor * vertcolor;\n"
"};\n"
;
